name = "kitscon241"
compatibility_date = "2024-04-05"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NOTES"
id = "252ff2b5de6a40c2b911c26c4d4297dd"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "4f17264a988248e4a1dd55ef363bd1d7"

[[services]]
binding = "DICE_ROLLER"
service = "kitscon241-diceroller"

[[services]]
binding = "DICE_ROLLER_RPC"
service = "kitscon241-diceroller"
entrypoint = "DiceRollerService"
