name = "kitscon241"
compatibility_date = "2024-04-05"

[ai]
binding = "AI"

[[d1_databases]]
binding = "NOTES_DB"
database_name = "kitscon241-db"
database_id = "6c11d0ca-a8e3-4c04-9f44-5594446c5b89"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "4f17264a988248e4a1dd55ef363bd1d7"

[[services]]
binding = "DICE_ROLLER"
service = "kitscon241-diceroller"

[[services]]
binding = "DICE_ROLLER_RPC"
service = "kitscon241-diceroller"
entrypoint = "DiceRollerService"
